version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nestjs_backend_dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      # - /app/node_modules
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: cms_password
      DB_NAME: holywater
    networks:
     - app_network
    

  db:
    image: postgres:latest
    container_name: nestjs_db_dev
    environment:
      POSTGRES_DB: holywater # Назва вашої БД
      POSTGRES_USER: admin # Користувач, який буде створений
      POSTGRES_PASSWORD: cms_password # Пароль користувача
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
     - app_network
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -d holywater -U admin"]
    #   interval: 10s
    #   retries: 20
    #   timeout: 5s
  redis:
    image: redis:latest
    container_name: nestjs_redis_dev
    environment:
      REDIS_USER: admin
      REDIS_PASSWORD: redis_password123
    restart: unless-stopped
    command:
      - redis-server
      - --requirepass ${REDIS_PASSWORD}
      - --user ${REDIS_USER} on +@all ~* >${REDIS_PASSWORD}
      - --appendonly yes
      - --save 60 1
      - --dbfilename dump.rdb
      - --dir /data
    ports:
      - "6379:6379"
    volumes:
      - $HOME/db-storage/redis-cms:/data
    networks:
      - app_network  

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
