version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod # Використовуємо Dockerfile для продакшену
    container_name: nestjs_backend_prod
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: my_user
      DB_PASSWORD: my_password
      DB_NAME: my_database

  db:
    image: postgres:13
    container_name: nestjs_db_prod
    environment:
      POSTGRES_DB: holywater
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: cms_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: